image: golang:latest

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN"
    - go version
    - go run ./cmd/main/Main.go

test-job:
  stage: test
  script:
    - go test ./cmd/...